/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-11 19:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/includes/side_pannel.jsp", Long.valueOf(1449858059000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/header.jsp", Long.valueOf(1449776714000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/meta.jsp", Long.valueOf(1449858004000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/stylesheets.jsp", Long.valueOf(1449858351000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/footer.jsp", Long.valueOf(1449758311000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\t\t \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("\t\"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<!-- BEGIN FIXME Voir si le false est justifié -->\n");
      out.write("\n");
      out.write("<!-- END -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<!-- EN-TÊTE DE LA PAGE (Meta-informations) -->\n");
      out.write("\t<head>\n");
      out.write("\t\t");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/base.css\" media=\"all\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/design.css\" media=\"screen\" />");
      out.write("\n");
      out.write("\t\t<title>Annuaire web - Erreur</title>\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<!-- CORPS DE LA PAGE -->\n");
      out.write("\t<body>\n");
      out.write("\t\t<!-- HEADER -->\n");
      out.write("\t\t");
      out.write("<div id=\"header\">\n");
      out.write("\t<h1>\n");
      out.write("\t\t<a href=\"home\" title=\"Page d'accueil\">\n");
      out.write("\t\t\t<!--<img id=\"logo\" alt=\"Logo\" src=\"avatar.png\" />-->\n");
      out.write("\t\t\t<span>Annuaire web</span>\n");
      out.write("\t\t</a>\n");
      out.write("\t</h1>\n");
      out.write("\t<h2>Faculté des Sciences - Aix-Marseille Université</h2>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- PANNEAU LATÉRAL -->\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\t\t \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("\t\"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<!-- BEGIN FIXME Voir si le false est justifié -->\n");
      out.write("\n");
      out.write("<!-- END -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- PANNEAU LATÉRAL -->\n");
      out.write("<div id=\"side_panel\">\n");
      out.write("\t<!-- NAVIGATION -->\n");
      out.write("    <div id=\"navigation\">\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("   \n");
      out.write("   \t\t<!-- CONTENU -->\n");
      out.write("\t\t<div id=\"contents\">\n");
      out.write("    \t\t<h2>/!\\ Oups... Une erreur est survenue</h2>\n");
      out.write("    \t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\n");
      out.write("    \t\t<p>Si le problème persiste, veuillez en informer l'administrateur de ce site.</p>\n");
      out.write("\t\t</div>\n");
      out.write("   \n");
      out.write("   \t\t<!-- FOOTER -->\n");
      out.write("\t\t");
      out.write("<p id=\"footer\">\n");
      out.write("\tAnnuaire web<br />\n");
      out.write("\tPar Amirdine MDJASSIRI et Charly CÉLÉREAU\n");
      out.write("</p>");
      out.write("\t    \n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/includes/side_pannel.jsp(8,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("g");
    // /WEB-INF/jsp/includes/side_pannel.jsp(8,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/includes/side_pannel.jsp(8,3) '${groupIterator}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${groupIterator}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<li>\n");
          out.write("\t\t    \t\t<a href=\"groups/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\n");
          out.write("\t\t    \t\t   title=\"Liste des membres du groupe ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\n");
          out.write("\t\t    \t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${g.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\n");
          out.write("\t\t    \t\t</a>\n");
          out.write("\t\t  \t\t</li>\t\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
